"""modify tables

Revision ID: b45431c057ba
Revises: e6382ac407b0
Create Date: 2023-12-15 21:32:43.616869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b45431c057ba'
down_revision: Union[str, None] = 'e6382ac407b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('Title', sa.Text(), nullable=False))
    op.add_column('movies', sa.Column('Poster', sa.VARCHAR(), nullable=False))
    op.drop_column('movies', 'image')
    op.drop_column('movies', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('title', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('movies', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('movies', 'Poster')
    op.drop_column('movies', 'Title')
    # ### end Alembic commands ###
